merge-anything/main/default/objects/Merge_Item__c/Merge_Item__c.object-meta.xml
<CustomObject>
    <label>Merge Item</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Merge Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

merge-anything/main/default/objects/Merge_Item__c/fields/Merge_Job__c.field-meta.xml
<CustomField>
    <fullName>Merge_Job__c</fullName>
    <label>Merge Job</label>
    <referenceTo>Merge_Job__c</referenceTo>
    <relationshipLabel>Merge Items</relationshipLabel>
    <relationshipName>Merge_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Merged_Record_JSON__c.field-meta.xml
<CustomField>
    <fullName>Merged_Record_JSON__c</fullName>
    <description>Merged JSON representation of primary and secondary record data.</description>
    <inlineHelpText>Merged JSON representation of primary and secondary record data.</inlineHelpText>
    <label>Merged Record JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Primary_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Primary_Record_Id__c</fullName>
    <description>The Id of the primary record.</description>
    <inlineHelpText>The Id of the primary record.</inlineHelpText>
    <label>Primary Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Primary_Record_JSON__c.field-meta.xml
<CustomField>
    <fullName>Primary_Record_JSON__c</fullName>
    <description>Original JSON representation of primary record data.</description>
    <inlineHelpText>Original JSON representation of primary record data.</inlineHelpText>
    <label>Primary Record JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Secondary_Record_Id__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Record_Id__c</fullName>
    <description>The Id of the secondary record.</description>
    <inlineHelpText>The Id of the secondary record.</inlineHelpText>
    <label>Secondary Record Id</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Secondary_Record_JSON__c.field-meta.xml
<CustomField>
    <fullName>Secondary_Record_JSON__c</fullName>
    <description>Original JSON representation of secondary record data.</description>
    <inlineHelpText>Original JSON representation of secondary record data.</inlineHelpText>
    <label>Secondary Record JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this merge item.</description>
    <inlineHelpText>The status of this merge item.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

merge-anything/main/default/objects/Merge_Job__c/Merge_Job__c.object-meta.xml
<CustomObject>
    <label>Merge Job</label>
    <nameField>
        <displayFormat>MJ-{000000}</displayFormat>
        <label>Merge Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merge-anything/main/default/objects/Merge_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

merge-anything/main/default/classes/MergeItemSelector.cls
public class MergeItemSelector {
    private static MergeItemSelector instance = new MergeItemSelector();

    @SuppressWarnings('PMD.EmptyStatementBlock')
    @TestVisible
    private MergeItemSelector() {
    }

    /**
     * @description The instance `MergeItemSelector` used for any querying specific to merge items
     * @return   The singleton instance of `MergeItemSelector`
     */
    public static MergeItemSelector getInstance() {
        return instance;
    }

    /**
     * @description Returns a list of `Merge_Item__c` records
     * @param  mergeItemIds The list of `ID` of the `Merge_Item__c` records to query
     * @return        The list of matching `Merge_Item__c` records
     */
    public List<Merge_Item__c> getMergeItemsById(List<Id> mergeItemIds) {
        return [
            SELECT
                Id,
                CreatedDate,
                Name,
                Merge_Job__c,
                Merged_Record_JSON__c,
                Primary_Record_Id__c,
                Primary_Record_JSON__c,
                Secondary_Record_Id__c,
                Secondary_Record_JSON__c,
                Status__c
            FROM Merge_Item__c
            WHERE Id IN :mergeItemIds
        ];
    }

    /**
     * @description Returns a list of `Merge_Item__c` records
     * @param  mergeJobId The single `Merge_Job__c` Id of the `Merge_Item__c` records to query
     * @return        The list of matching `Merge_Item__c` records
     */
    public List<Merge_Item__c> getMergeItemsByMergeJobId(Id mergeJobId) {
        return [
            SELECT
                Id,
                CreatedDate,
                Name,
                Merge_Job__c,
                Merged_Record_JSON__c,
                Primary_Record_Id__c,
                Primary_Record_JSON__c,
                Secondary_Record_Id__c,
                Secondary_Record_JSON__c,
                Status__c
            FROM Merge_Item__c
            WHERE Merge_Job__c = :mergeJobId
        ];
    }
}