merge-anything/main/default/objects/Merge_Item__c/Merge_Item__c.object-meta.xml
<CustomObject>
    <label>Merge Item</label>
    <nameField>
        <displayFormat>MI-{000000}</displayFormat>
        <label>Merge Item Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Items</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

merge-anything/main/default/objects/Merge_Item__c/fields/Merge_Job__c.field-meta.xml
<CustomField>
    <fullName>Merge_Job__c</fullName>
    <label>Merge Job</label>
    <referenceTo>Merge_Job__c</referenceTo>
    <relationshipLabel>Merge Items</relationshipLabel>
    <relationshipName>Merge_Items</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

merge-anything/main/default/objects/Merge_Item__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>The status of this merge item.</description>
    <inlineHelpText>The status of this merge item.</inlineHelpText>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
                <default>true</default>
                <label>Pending</label>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

merge-anything/main/default/objects/Merge_Job__c/Merge_Job__c.object-meta.xml
<CustomObject>
    <label>Merge Job</label>
    <nameField>
        <displayFormat>MJ-{000000}</displayFormat>
        <label>Merge Job Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Jobs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merge-anything/main/default/objects/Merge_Job__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Pending</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
            <value>
                <fullName>Failed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

merge-anything/main/default/classes/MergeJob.cls
public class MergeJob {
    @AuraEnabled
    public Merge_Job__c mergeJob { get; private set; }
    @AuraEnabled
    public List<Merge_Item__c> mergeItems { get; private set; }
    @AuraEnabled
    public List<String> errors { get; private set; }

    public MergeJob() {
        this.mergeJob = new Merge_Job__c();
        this.mergeItems = new List<Merge_Item__c>();

        this.init();
    }

    public MergeJob(Merge_Job__c mergeJob) {
        this.mergeJob = mergeJob;
        this.mergeItems = new List<Merge_Item__c>();

        this.init();
    }

    public MergeJob(Merge_Job__c mergeJob, List<Merge_Item__c> mergeItems) {
        this.mergeJob = mergeJob;
        this.mergeItems = mergeItems;

        this.init();
    }

    private void init() {
        this.errors = new List<String>();
        this.setStatus(MergeAnythingConstants.MERGE_JOB_STATUS.PENDING);
    }

    public void setStatus(String status) {
        this.mergeJob.Status__c = status;
    }

    public void addMergeItem(Merge_Item__c mergeItem) {
        this.mergeItems.add(mergeItem);
    }

    public MergeJob create() {
        Database.SaveResult sr = Database.insert(this.mergeJob, false);
        if (!sr.isSuccess()) {
            for (Database.Error objErr : sr.getErrors()) {
                this.errors.add(objErr.getStatusCode() + ': ' + objErr.getMessage());
                this.errors.add('Invoice oject field which are affected by the error:' + objErr.getFields());
            }
        } else {
            this.mergeJob = MergeJobSelector.getInstance().getMergeJobById(sr.getId());
        }
        return this;
    }
}