merge-anything/main/default/objects/Merge_Field_Template__c/Merge_Field_Template__c.object-meta.xml
<CustomObject>
    <label>Merge Field Template</label>
    <nameField>
        <displayFormat>MFT-{00000}</displayFormat>
        <label>Template Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Merge Field Templates</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

merge-anything/main/default/objects/Merge_Field_Template__c/fields/Field_Selections_JSON__c.field-meta.xml
<CustomField>
    <fullName>Field_Selections_JSON__c</fullName>
    <label>Field Selections JSON</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

merge-anything/main/default/objects/Merge_Field_Template__c/fields/Target_Object__c.field-meta.xml
<CustomField>
    <fullName>Target_Object__c</fullName>
    <label>Target Object</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

merge-anything/main/default/classes/MergeFieldTemplateSelector.cls
public with sharing class MergeFieldTemplateSelector {
    private static MergeFieldTemplateSelector instance = new MergeFieldTemplateSelector();

    @SuppressWarnings('PMD.EmptyStatementBlock')
    @TestVisible
    private MergeFieldTemplateSelector() {
    }

    public static MergeFieldTemplateSelector getInstance() {
        return instance;
    }

    public List<Merge_Field_Template__c> getTemplatesForObject(String targetObjectApiName) {
        if (String.isBlank(targetObjectApiName)) {
            return new List<Merge_Field_Template__c>();
        }
        return [
            SELECT Id, Name, Target_Object__c, Field_Selections_JSON__c, Description__c
            FROM Merge_Field_Template__c
            WHERE Target_Object__c = :targetObjectApiName
            WITH SECURITY_ENFORCED
            ORDER BY CreatedDate DESC
        ];
    }
}